### ISSUE TITLE
Could you please check my fork?

### ISSUE THREAD

**Issue by nassarofficial** [oot77/swift-C-string-passing#1]
Hello, I think I might be asking much, but I dont know what to do more, I forked and added my code but it isn't printing anything in the console. I know I didn't set the printout to text yet, but I cant get output to console yet working.

**Comment by oot77** [comment]
You must at least use the #define statements to reroute the printf s to tprntf and so on... (don't forget the tprntNewLine(); at the end).

But looking at the C code there's a lot more to modify if you want to get that running - no cheap trick here - sorry.

The most important part would be to get a method for changing the user input in the C code, thats not trivial!

At the moment (and in my example) its easy, because we just pass some strings to the main function and collect the output.
But that won't work  with something like (in your mymain):
while(TRUE) { ... if (ja()) {} } 
You're out of the loop there )-: you have no interaction possibility from swift there.
You would have to recode the C game to stop at every user input and pass the control to swift - collect the input there and then pass it back to the game ...

**Comment by nassarofficial** [comment]
Thank you for the response, I was looking for the cheap trick :D.
